MENU = [
    {
        "id": "pizza_margherita",
        "name": "Pizza Margherita",
        "beschreibung": "Tomatensauce, Mozzarella, Basilikum",
        "kategorie": "Pizza",
        "preis": 8.5,
    },
    {
        "id": "pizza_salami",
        "name": "Pizza Salami",
        "beschreibung": "Tomatensauce, Mozzarella, scharfe Salami",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_funghi",
        "name": "Pizza Funghi",
        "beschreibung": "Tomatensauce, Mozzarella, frische Champignons",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_prosciutto",
        "name": "Pizza Prosciutto",
        "beschreibung": "Tomatensauce, Mozzarella, gekochter Schinken",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_quattro_formaggi",
        "name": "Pizza Quattro Formaggi",
        "beschreibung": "Vier Käsesorten",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_hawaii",
        "name": "Pizza Hawaii",
        "beschreibung": "Schinken, Ananas, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_diavola",
        "name": "Pizza Diavola",
        "beschreibung": "Scharfe Salami, Chili, Paprika",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_tonno",
        "name": "Pizza Tonno",
        "beschreibung": "Thunfisch, Zwiebeln",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_spinaci",
        "name": "Pizza Spinaci",
        "beschreibung": "Spinat, Knoblauch, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_vegetariana",
        "name": "Pizza Vegetariana",
        "beschreibung": "Gemüse der Saison",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_rucola",
        "name": "Pizza Rucola",
        "beschreibung": "Rucola, Parmesan, Rohschinken",
        "kategorie": "Pizza",
        "preis": 10.5,
    },
    {
        "id": "pizza_frutti_di_mare",
        "name": "Pizza Frutti di Mare",
        "beschreibung": "Meeresfrüchte, Knoblauch",
        "kategorie": "Pizza",
        "preis": 11.5,
    },
    {
        "id": "pizza_calzone",
        "name": "Pizza Calzone",
        "beschreibung": "Gefaltete Pizza mit Salami und Schinken",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_capricciosa",
        "name": "Pizza Capricciosa",
        "beschreibung": "Schinken, Pilze, Artischocken, Oliven",
        "kategorie": "Pizza",
        "preis": 10.5,
    },
    {
        "id": "pizza_bufala",
        "name": "Pizza Bufala",
        "beschreibung": "Büffelmozzarella, Basilikum",
        "kategorie": "Pizza",
        "preis": 11.0,
    },
    {
        "id": "pizza_pesto",
        "name": "Pizza Pesto",
        "beschreibung": "Grünes Pesto, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_zucchini",
        "name": "Pizza Zucchini",
        "beschreibung": "Gegrillte Zucchini, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_melanzane",
        "name": "Pizza Melanzane",
        "beschreibung": "Aubergine, Knoblauch, Käse",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_gorgonzola",
        "name": "Pizza Gorgonzola",
        "beschreibung": "Gorgonzola, Walnüsse",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_piccante",
        "name": "Pizza Piccante",
        "beschreibung": "Scharfe Peperoni, Chiliöl",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_salsiccia",
        "name": "Pizza Salsiccia",
        "beschreibung": "Italienische Wurst, Zwiebeln",
        "kategorie": "Pizza",
        "preis": 10.5,
    },
    {
        "id": "pizza_patate",
        "name": "Pizza Patate",
        "beschreibung": "Kartoffelscheiben, Rosmarin, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_bresaola",
        "name": "Pizza Bresaola",
        "beschreibung": "Bresaola, Rucola, Parmesan",
        "kategorie": "Pizza",
        "preis": 11.5,
    },
    {
        "id": "pizza_pancetta",
        "name": "Pizza Pancetta",
        "beschreibung": "Italienischer Speck, Ei",
        "kategorie": "Pizza",
        "preis": 10.5,
    },
    {
        "id": "pizza_carbonara",
        "name": "Pizza Carbonara",
        "beschreibung": "Carbonara-Sauce auf Pizza",
        "kategorie": "Pizza",
        "preis": 10.0,
    },
    {
        "id": "pizza_speck",
        "name": "Pizza Speck",
        "beschreibung": "Geräucherter Speck, Zwiebeln",
        "kategorie": "Pizza",
        "preis": 9.5,
    },
    {
        "id": "pizza_champignon",
        "name": "Pizza Champignon",
        "beschreibung": "Extra Pilze, Mozzarella",
        "kategorie": "Pizza",
        "preis": 9.0,
    },
    {
        "id": "pizza_extra_mozzarella",
        "name": "Pizza Extra Mozzarella",
        "beschreibung": "Extra Mozzarella",
        "kategorie": "Pizza",
        "preis": 8.5,
    },
    {
        "id": "pizza_pomodoro",
        "name": "Pizza Pomodoro",
        "beschreibung": "Tomaten in Scheiben, Basilikum",
        "kategorie": "Pizza",
        "preis": 8.0,
    },
    {
        "id": "pizza_tartufo",
        "name": "Pizza Tartufo",
        "beschreibung": "Trüffelcreme, Pilze",
        "kategorie": "Pizza",
        "preis": 12.0,
    },
    # 🍝 Weitere Speisen & Getränke
    {
        "id": "lasagne",
        "name": "Lasagne",
        "beschreibung": "Mit Rindfleisch und Bechamelsauce",
        "kategorie": "Pasta",
        "preis": 10.0,
    },
    {
        "id": "tiramisu",
        "name": "Tiramisu",
        "beschreibung": "Mit Mascarpone und Espresso",
        "kategorie": "Dessert",
        "preis": 5.0,
    },
    {
        "id": "cola",
        "name": "Cola",
        "beschreibung": "0.33l Erfrischungsgetränk",
        "kategorie": "Getränk",
        "preis": 2.5,
    },
    {
        "id": "spritz",
        "name": "Aperol Spritz",
        "beschreibung": "Aperitif mit Prosecco",
        "kategorie": "Getränk",
        "preis": 5.5,
    },
    {
        "id": "teqsun",
        "name": "Tequila Sunrise",
        "beschreibung": "Leckerer Cocktail",
        "kategorie": "Getränk",
        "preis": 5.5,
    },
    {
        "id": "campari",
        "name": "Campari",
        "beschreibung": "Bitterer Aperitiv auf Eis",
        "kategorie": "Getränk",
        "preis": 5.5,
    },
    {
        "id": "insalata_mista",
        "name": "Insalata Mista",
        "beschreibung": "Gemischter Salat mit Dressing",
        "kategorie": "Salat",
        "preis": 6.0,
    },
    {
        "id": "bruschetta",
        "name": "Bruschetta",
        "beschreibung": "Geröstetes Brot mit Tomaten",
        "kategorie": "Vorspeise",
        "preis": 4.5,
    },
    {
        "id": "minestrone",
        "name": "Minestrone",
        "beschreibung": "Italienische Gemüsesuppe",
        "kategorie": "Suppe",
        "preis": 5.0,
    },
    {
        "id": "risotto",
        "name": "Risotto",
        "beschreibung": "Mit Pilzen und Parmesan",
        "kategorie": "Reisgericht",
        "preis": 10.0,
    },
    {
        "id": "espresso",
        "name": "Espresso",
        "beschreibung": "Starker Kaffee",
        "kategorie": "Getränk",
        "preis": 2.0,
    },
    {
        "id": "panna_cotta",
        "name": "Panna Cotta",
        "beschreibung": "Mit Beerensauce",
        "kategorie": "Dessert",
        "preis": 5.0,
    },
]
